### ISSUE TITLE
Ethlogger resulting nulls

### ISSUE THREAD

**Issue by shravankumar147** [splunk/splunk-connect-for-ethereum#88]
I have created a virtual image on Azure, and setup docker for splunk-connect-for-ethereum. 

When I tried to see the network stats, I could not see any. I used search to review the transactions data, observed it is null. 

Have you been in this situation, what I could do to get the data properly.

**Comment by atoulme** [comment]
This denotes an issue with the collection process.
You might want to look at the logs of the ethlogger container: `docker logs ethlogger`

**Comment by j4ys0n** [comment]
If you're using infura, you'll want to disable a few things you currently have enabled.
set `COLLECT_PENDING_TX=false` and `COLLECT_PEER_INFO=false` as infura won't serve that data.

the last few lines of your logs show that splunk is either not yet ready or isn't available at the specified address.
```
2021-08-12T14:06:38.597Z ethlogger:hec:warn HEC service not (yet) available: HEC service https://splunk:8088/services/collector/event/1.0 not available: FetchError: request to https://splunk:8088/services/collector/health failed, reason: connect ECONNREFUSED 172.19.0.2:8088
2021-08-12T14:06:38.598Z ethlogger:hec:info Waiting for HEC service https://splunk:8088/services/collector/event/1.0 to become available (timeout 120000 ms)
```
in your first post, it sounds like you have Splunk running, so check that you are pointing ethlogger to the correct location.

**Comment by j4ys0n** [comment]
Those are set in the environment variables section of the docker compose file you're using for ethlogger.

**Comment by shravankumar147** [comment]
Great, found here, https://github.com/splunk/splunk-connect-for-ethereum/blob/master/docs/cli.md#environment-variables

On the otherhand, was there any issue with this SPLUNK_HEC_URL=https://splunk.com:8088, as I am testing on Azure VM.

**Comment by shravankumar147** [comment]
I have set these, 
            - COLLECT_PENDING_TX=false
            - COLLECT_PEER_INFO=false
            - START_AT_BLOCK=latest
            - SPLUNK_HEC_URL=https://splunk:8088
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_EVENTS_INDEX=main
            - SPLUNK_METRICS_INDEX=metrics
            - SPLUNK_INTERNAL_INDEX=metrics
            - SPLUNK_HEC_REJECT_INVALID_CERTS=false
            - ABI_DIR=/app/abis


Yet I am unable to get data, 
2021-08-12T15:12:46.810Z ethlogger:cli:info Starting ethlogger version=@splunkdlt/ethlogger/3.0.1 linux-x64 node-v14.16.1 git-sha=77a9d95bb13e120b761723680d6ab1e1e63919bd
2021-08-12T15:12:46.813Z ethlogger:introspect:info Introspecting target ethereum node at jsonprc+https://mainnet.infura.io
2021-08-12T15:12:47.123Z ethlogger:introspect:info Retrieved ethereum node version: Geth/v1.10.6-omnibus-f00fbaa2/linux-amd64/go1.16.6
2021-08-12T15:12:47.183Z ethlogger:platforms:generic:warn Ethereum node failed to respond to protocol version request JsonRpcError: The method admin_nodeInfo does not exist/is not available
    at Object.checkError (/ethlogger/lib/eth/jsonrpc.js:31:15)
    at HttpTransport.sendInternal (/ethlogger/lib/eth/http.js:109:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async HttpTransport.sendBatch (/ethlogger/lib/eth/http.js:62:24)
    at async executeBatchRequest (/ethlogger/lib/eth/client.js:17:25)
    at async Timeout.BatchedEthereumClient.processQueue (/ethlogger/lib/eth/client.js:97:20) {
  code: -32601,
  data: undefined
}
2021-08-12T15:12:47.186Z ethlogger:introspect:warn Failed to initialize node platform adapter: The method admin_nodeInfo does not exist/is not available
2021-08-12T15:12:47.186Z ethlogger:introspect:info Attempting to use generic node platform adapter: generic:unknown
2021-08-12T15:12:47.308Z ethlogger:platforms:generic:warn RPC method eth_pendingTransactions is not supported by ethereum node: The method eth_pendingTransactions does not exist/is not available
2021-08-12T15:12:47.416Z ethlogger:cli:info Detected node platform='generic:Geth' protocol=65 chainId=1 networkId=1 chain=mainnet network=eth
2021-08-12T15:12:47.427Z ethlogger:hec:warn HEC service not (yet) available: HEC service https://splunk:8088/services/collector/event/1.0 not available: FetchError: request to https://splunk:8088/services/collector/health failed, reason: connect ECONNREFUSED 172.26.0.2:8088
2021-08-12T15:12:47.428Z ethlogger:hec:info Waiting for HEC service https://splunk:8088/services/collector/event/1.0 to become available (timeout 120000 ms)
2021-08-12T15:13:20.980Z ethlogger:hec:info HEC service is now available after 33560 ms
2021-08-12T15:13:20.983Z ethlogger:checkpoint:info Found existing checkpoints: { initialBlockNumber: 17551058, completedBlockCount: 211 }
2021-08-12T15:13:20.984Z ethlogger:abi:repo:info Loaded 0 ABIs from directory /app/abis
2021-08-12T15:13:22.744Z ethlogger:abi:repo:info Loaded 185079 anonymous ABI signatures from built-in signature files
2021-08-12T15:13:22.982Z ethlogger:nodestats:info Collected node info in 236 ms
2021-08-12T15:13:22.983Z ethlogger:nodestats:info Collected node metrics in 237 ms

**Comment by j4ys0n** [comment]
it looks like data is going into Splunk now.
```
2021-08-12T15:13:20.980Z ethlogger:hec:info HEC service is now available after 33560 ms
2021-08-12T15:13:20.983Z ethlogger:checkpoint:info Found existing checkpoints: { initialBlockNumber: 17551058, completedBlockCount: 211 }
```
search for `index=*` in Splunk.

**Comment by shravankumar147** [comment]
I have stopped everything, and cloned a fresh repository `https://github.com/splunk/splunk-connect-for-ethereum.git`

`cd  ~/splunk-connect-for-ethereum/examples/docker-compose-basic`

Then edited dockecr-compose.yaml as below: 

Commented dxai
Uncommented ETH mainnet with infura project id

added 
            - COLLECT_PENDING_TX=false
            - COLLECT_PEER_INFO=false

```
version: '3.6'

services:
    splunk:
        image: splunk/splunk:latest
        container_name: splunk
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_PASSWORD=changeme
            - SPLUNK_APPS_URL=https://github.com/splunk/ethereum-basics/releases/download/latest/ethereum-basics.tgz
        ports:
            - 8000:8000
            - 8088:8088
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000']
            interval: 5s
            timeout: 5s
            retries: 20
        volumes:
            - ./splunk.yml:/tmp/defaults/default.yml
            - /opt/splunk/var
            - /opt/splunk/etc
    ethlogger:
        image: ghcr.io/splunkdlt/ethlogger:latest
        container_name: ethlogger
        environment:
                #- ETH_RPC_URL=https://dai.poa.network
            # Use these environment variables to connect to infura
            - ETH_RPC_URL=https://mainnet.infura.io/v3/<your-infura-project-id>
            - COLLECT_PENDING_TX=false
            - COLLECT_PEER_INFO=false
            - START_AT_BLOCK=latest
            - SPLUNK_HEC_URL=https://splunk:8088
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_EVENTS_INDEX=main
            - SPLUNK_METRICS_INDEX=metrics
            - SPLUNK_INTERNAL_INDEX=metrics
            - SPLUNK_HEC_REJECT_INVALID_CERTS=false
            - ABI_DIR=/app/abis
        volumes:
            - ./abis:/app/abis
            - ./:/app
        depends_on:
            - splunk
        restart: always

```

saved and ran

docker-compose up -d

Checked splunk: I could see logs now. 

![image](https://user-images.githubusercontent.com/9673411/129228918-f9121e69-d66b-42be-8c5a-118ae2042481.png)

I suspect, starting dxai, then stopping docker to change to ETH and rerunning causing the problem. 

Finally by starting with a fresh chain from beginning helped me to solve this issue, and able to see the output. 

Thanks
Shravan
